### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by delitescere**
- Add: set -u to error on reference of unset variables
- Add: how to handle possibly un-exported environment variables when `set -u`
- Add: split declaration and command substitution assignment to ensure `set -e` works
- Add: default `TRACE` to null string to avoid failing when `set -u`
- Add: example of these things in action
- Add: unquestionably no hard tabs, and 2-space indentation
- Cleanup: trailing periods on list items
- Cleanup: convert hard tabs in examples to 2-space indentation

### CODE REVIEW

**Comment by progrium** [comment]
Okay, yes. I wouldn't make it a rule to split all declaration and assignment, but make it clear that you should do that when you care about the potential error. There are plenty of assignments that are "safe" like when you aren't using command substitution.

Can you explain the hard opinion on tabs vs spaces? I've not seen a compelling argument one way or the other for bash, hence I don't really care.

**Comment by progrium** [comment]
This issue has convinced me to use hard tabs: https://github.com/progrium/bashstyle/issues/23

**Comment by delitescere** [comment]
That certainly is compelling, if you're generating text files using heredocs, or sending them to programs which do not like leading tabs in the input (any?).

As I explain here https://github.com/progrium/bashstyle/issues/23#issuecomment-70010724, I use heredocs often to generate other scripts, so the spacing and indentation reset is desirable for me. 

But, wow. Bash. Always surprising.

**Comment by delitescere** [comment]
Agreed on the split decl/assignment warning. In fact, I don't split if I'm assigning without command substitution.

I don't care about the spaces either. I was just cleaning up the formatting to be one-or-other as the pre-PR code had a smattering.

I used to be a tabs man (1 character instead of 2, 4, or 8? Yes please), but after years of pairing / OSS with different people's tab settings, I was convinced that 2-spaces everywhere was least error-prone, legible, maximized horizontal real estate, and most common in the communities who languages I used. Like ANSI v K&R braces, I changed twice in the past 25 years, I may one day change on tabs (at least for bash).

**Comment by progrium** [comment]
So maybe rework this PR to focus on the split decl/assignment?

**Pull request closed without merging**
